name: Tflint


on:
  pull_request:
permissions:
  contents: read

jobs:
  tflint:
    permissions:
      contents: read
    runs-on: test-arc-runner-set
    strategy:
      matrix:
        path:
          - .
    steps:
    - uses: makandra/github-actions/tflint@main
      with:
        path: ${{ matrix.path }}
